<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[21]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[20]=array(0,1,1,'5Lqk5rWB5LqS5Yqo');
$cfg_Cs[19]=array(0,1,1,'5Yqe5LqL5oyH5Y2X');
$cfg_Cs[18]=array(0,1,1,'6K6h5YiS55Sf6IKy');
$cfg_Cs[17]=array(0,1,1,'5aWz5bel5LmL56qX');
$cfg_Cs[16]=array(13,1,1,'5aaH5aWz5p2D55uK5L+d5oqk5rOV');
$cfg_Cs[12]=array(0,1,1,'5bel5Lya5qaC5Ya1');
$cfg_Cs[13]=array(0,1,1,'5pS/562W5rOV6KeE');
$cfg_Cs[14]=array(13,1,1,'5bel5Lya56ug56iL');
$cfg_Cs[15]=array(13,1,1,'5bel5Lya5rOV');
?>