<?php
$z[0]=Array("field","",62,90);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",92,121);
$z[1][4]['name']="typename";
$z[2]=Array("field","",185,213);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n          <li>\r\n            <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n            <span>[[field:pubdate function=\"MyDate('m-d',@me)\"/]]</span>\r\n          </li>\r\n          ",326,556);
$z[3][4]['titlelen']="40";
$z[3][4]['row']="7";

?>