<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",169,186);
$z[2]=Array("arcurl","",201,216);
$z[3]=Array("title","",232,246);
$z[4]=Array("pubdate","",295,341);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",366,380);
$z[6]=Array("scores","",405,420);
$z[7]=Array("description","",452,472);

?>