<?php
$z[0]=Array("field","",43,71);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",73,102);
$z[1][4]['name']="typename";
$z[2]=Array("field","",143,171);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\n      <li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\n      ",240,431);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>