<?php
$z[0]=Array("global","",360,386);
$z[0][4]['name']="cfg_version";
$z[1]=Array("global","",518,543);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channelartlist","\r\n	<ul id=\"dropmenu{dede:field.typeid/}\" class=\"dropMenu\">\r\n		{dede:channel type='son' typeid noself='yes'} \r\n			<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n		{/dede:channel}\r\n	</ul>\r\n	",579,847);
$z[2][4]['type']="top";
$z[2][4]['typeid']="top";

?>