<?php
$z[0]=Array("global","",184,209);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",275,300);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",362,387);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",420,446);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",574,601);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",674,701);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",704,730);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",910,937);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",949,981);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1028,1054);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",1441,1466);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\r\n        <li [field:rel/]><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n        ",1516,1774);
$z[11][4]['type']="top";
$z[11][4]['row']="9";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[12]=Array("global","",1871,1896);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2704,2834);
$z[13][4]['row']="10";
$z[13][4]['getall']="1";
$z[13][4]['sort']="month";

?>