<?php
$z[0]=Array("global","",184,209);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",275,300);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",362,387);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",420,446);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",574,601);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",674,701);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",704,730);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",910,937);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",949,981);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1028,1054);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1109,1144);
$z[10][4]['name']="innerTopBanner1";
$z[11]=Array("myad","",1179,1214);
$z[11][4]['name']="innerTopBanner2";
$z[12]=Array("global","",1733,1758);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1804,2047);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",2144,2169);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2977,3107);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>