<?php
$z[0]=Array("global","",238,266);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",281,307);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",353,383);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",422,449);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",469,501);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",703,729);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",823,849);
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("global","",953,985);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("include","",1075,1110);
$z[8][4]['filename']="head.htm";
$z[9]=Array("include","",1169,1206);
$z[9][4]['filename']="slider.htm";
$z[10]=Array("channelartlist","\r\n    <dl class=\"tbox light\">\r\n      <dt>\r\n        <strong><a href=\"{dede:field name='typeurl'/}\">&#9830;{dede:field name='typename'/}&#9830;</a></strong> \r\n        <span class=\"more\">\r\n          <a href=\"{dede:field name='typeurl'/}\">更多</a>\r\n        </span>\r\n      </dt>\r\n      <dd class='light'>\r\n        <ul class=\"d1 ico3\">\r\n          {dede:arclist titlelen='40' row='6'}\r\n          <li>\r\n            <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n            <span>[[field:pubdate function=\"MyDate('m-d',@me)\"/]]</span>\r\n          </li>\r\n          {/dede:arclist}\r\n        </ul>\r\n      </dd>\r\n    </dl>\r\n    ",1245,1924);
$z[10][4]['typeid']="26,27,28";
$z[11]=Array("arclist","\r\n                    <li>\r\n                      <a href=\"[field:arcurl/]\">\r\n                        [field:image/]\r\n                        <span class=\"title\">[field:title/]</span>\r\n                      </a>\r\n                    </li>\r\n                    ",2245,2613);
$z[11][4]['row']="10";
$z[11][4]['orderby']="pubdate";
$z[11][4]['type']="image.";
$z[11][4]['typeid']="26";
$z[11][4]['imgwidth']="100";
$z[11][4]['imgheight']="60";
$z[12]=Array("include","",2843,2880);
$z[12][4]['filename']="footer.htm";
$z[13]=Array("myad","",2904,2937);
$z[13][4]['name']="floating-news";

?>