<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",671,706);
$z[6][4]['filename']="head.htm";
$z[7]=Array("channel","\r\n  <li [field:rel/]><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n  ",816,1042);
$z[7][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[8]=Array("field","",1143,1172);
$z[8][4]['name']="position";
$z[9]=Array("type","[field:reid/]",1221,1257);
$z[10]=Array("list","\r\n    <li> \r\n     <a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a>  <b>[field:pubdate function=\"GetDateMK(@me)\"/]</b>\r\n    </li>\r\n    ",1335,1515);
$z[10][4]['pagesize']="5";
$z[11]=Array("pagelist","",1605,1676);
$z[11][4]['listitem']="info,index,end,pre,next,pageno";
$z[11][4]['listsize']="5";
$z[12]=Array("global","",1833,1859);
$z[12][4]['name']="cfg_cmspath";
$z[13]=Array("include","",1888,1925);
$z[13][4]['filename']="footer.htm";

?>