<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",671,706);
$z[6][4]['filename']="head.htm";
$z[7]=Array("channelartlist","\r\n    <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n    ",818,977);
$z[7][4]['type']="top";
$z[7][4]['typeid']="10";
$z[8]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",1159,1278);
$z[8][4]['row']="10";
$z[8][4]['orderby']="click";
$z[9]=Array("field","",1413,1442);
$z[9][4]['name']="position";
$z[10]=Array("global","",1570,1596);
$z[10][4]['name']="cfg_cmspath";
$z[11]=Array("include","",1625,1662);
$z[11][4]['filename']="footer.htm";

?>