<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",671,706);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",818,843);
$z[7][4]['name']="reid";
$z[8]=Array("channel","\r\n    <li [field:rel/]><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n    ",853,1083);
$z[8][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[9]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",1272,1391);
$z[9][4]['row']="10";
$z[9][4]['orderby']="click";
$z[10]=Array("field","",1526,1555);
$z[10][4]['name']="position";
$z[11]=Array("global","",1683,1709);
$z[11][4]['name']="cfg_cmspath";
$z[12]=Array("include","",1738,1775);
$z[12][4]['filename']="footer.htm";

?>